name: Deploy Production Environment
on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
jobs:
  publish:
    environment: production
    name: Build and push docker image
    runs-on: ubuntu-latest
    steps: 
      - name: docker setup
        uses: docker/setup-docker-action@v4.3.0
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_ACCESS_SECRET_ID }}
          aws-region: us-east-1
      - name: Login to Amazon ECR Public
        run: |
          aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${{ secrets.ECR_REGISTRY }}
      - name: Checkout
        uses: actions/checkout@v4
      - name: Docker build
        run: |
          docker build . -t ${{ vars.DOCKER_IMAGE_NAME }}
      - name: Docker tag
        run: docker tag ${{ vars.DOCKER_IMAGE_NAME }}:latest ${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_NAMESPACE }}/${{ vars.DOCKER_IMAGE_NAME }}:latest
      - name: Docker push
        run: docker push ${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_NAMESPACE }}/${{ vars.DOCKER_IMAGE_NAME }}:latest
      
  deploy:
    needs: publish
    environment: production
    runs-on: sh-05_gateway
    steps:
      - name: Docker pull
        run: |
          sudo docker pull ${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_NAMESPACE }}/${{ vars.DOCKER_IMAGE_NAME }}:latest
      - name: Deploy with docker run
        run: |
          sudo docker stop ${{ vars.DOCKER_CONTAINER_NAME }} || true
          sudo docker rm ${{ vars.DOCKER_CONTAINER_NAME }} || true
          sudo docker run -d --name ${{ vars.DOCKER_CONTAINER_NAME }} \
            -p ${{ vars.DOCKER_CONTAINER_PORT }}:8080 \
            -e MYSQL_HOST=${{ secrets.ENV_MYSQL_HOST }} \
            -e MYSQL_USER=${{ secrets.ENV_MYSQL_USER }} \
            -e MYSQL_PASSWORD=${{ secrets.ENV_MYSQL_PASSWORD }} \
            -e MYSQL_DATABASE=${{ secrets.ENV_MYSQL_DATABASE }} \
            -e REDIS_HOST=${{ secrets.ENV_REDIS_HOST }} \
            -e REDIS_PORT=${{ secrets.ENV_REDIS_PORT }} \
            -e REDIS_DB=${{ secrets.ENV_REDIS_DB }} \
            -e TOKEN=${{ secrets.ENV_TOKEN }} \
            -e XNXQDM=${{ vars.ENV_XNXQ }} \
            -e PAGE_SIZE=${{ vars.ENV_PAGE_SIZE }} \
            -e COOKIE=${{ secrets.ENV_COOKIE }} \
            -e JWXT_DOMAIN=${{ secrets.ENV_JWXT_DOMAIN }} \
            ${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_NAMESPACE }}/${{ vars.DOCKER_IMAGE_NAME }}:latest